#!/usr/bin/env python3
"""Save lz4 and decompressed versions of the firefox recovery.json file.

    Supported input: json or jsonlz4 recovery files

    Inspired by: https://gist.github.com/tmonjalo/33c4402b0d35f1233020bf427b5539fa

"""

DECOMPRESS = False     # do we want to save the decompressed version?

import time
import lz4.block
import shutil

timestamp = time.strftime( "%Y-%m-%dT%H:%M:%S", time.localtime())
DEFAULT =  "/home/darren/.mozilla/firefox/u6g0fs57.default/sessionstore-backups/recovery.jsonlz4"
OUTFILE = "firefox-recovery-%s.json" % timestamp


if __name__ == '__main__':

    # make a copy of the original recovery.jsonlz4 file.
    shutil.copyfile(DEFAULT, OUTFILE+"lz4")
    print("firefox-recovery-%s.jsonlz4 written." % timestamp)

    if DECOMPRESS:
        # decompress the lz4 format
        window_number = 0
        file_obj = open(DEFAULT, "rb")
        b = file_obj.read()
        if b[:8] == b'mozLz40\0':
            b = lz4.block.decompress(b[8:])

        # write out the decompressed version
        g = open(OUTFILE, "wb")
        g.write(b)
        g.close()
        print("firefox-recovery-%s.json written." % timestamp)
